//! Temporal tests over auto-generated corpus cases.
//!
//! Those cases are a holding area: they pin behaviour on a large, noisy
//! dump until the same fact can be restated as a small targeted test in
//! this crate. They churn often and they are bulky, so they are not part
//! of the project — this script only pulls them in when a local overlay
//! is pointed at (`$DEHOSK_OVERLAY` / `$DEHOSK_OVERLAY_TESTS`, or the
//! workspace pointer file). The published tree stays the targeted suite.

use std::path::{Path, PathBuf};

fn env_dir(name: &str) -> Option<PathBuf> {
    match std::env::var(name) {
        Ok(dir) if !dir.is_empty() => Some(PathBuf::from(dir)),
        _ => None,
    }
}

fn overlay_root(manifest_dir: &Path) -> Option<PathBuf> {
    if let Some(dir) = env_dir("DEHOSK_OVERLAY") {
        return Some(dir);
    }
    let workspace = manifest_dir.parent()?;
    let text = std::fs::read_to_string(workspace.join(".dehosk-overlay")).ok()?;
    let line = text
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty() && !line.starts_with('#'))?;
    let path = PathBuf::from(line);
    Some(if path.is_absolute() {
        path
    } else {
        workspace.join(path)
    })
}

fn temporal_sources(dir: &Path) -> Vec<(String, PathBuf)> {
    let mut out = Vec::new();
    let Ok(entries) = std::fs::read_dir(dir) else {
        return out;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        if stem == "polarity_oracle" || stem.starts_with("decompile_tests_") {
            out.push((stem.to_string(), path));
        }
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn main() {
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    let manifest =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    println!("cargo:rerun-if-env-changed=DEHOSK_OVERLAY");
    println!("cargo:rerun-if-env-changed=DEHOSK_OVERLAY_TESTS");
    if let Some(workspace) = manifest.parent() {
        println!(
            "cargo:rerun-if-changed={}",
            workspace.join(".dehosk-overlay").display()
        );
    }

    let tests_dir = env_dir("DEHOSK_OVERLAY_TESTS")
        .or_else(|| overlay_root(&manifest).map(|root| root.join("tests")));

    let mut generated = String::from("// Generated by build.rs.\n");
    if let Some(tests_dir) = tests_dir {
        println!("cargo:rerun-if-changed={}", tests_dir.display());
        let files = temporal_sources(&tests_dir);
        if !files.is_empty() {
            generated.push_str(
                "#[cfg(test)]\n\
                 #[allow(dead_code, unused_imports)]\n\
                 mod temporal {\n\
                     use super::*;\n\
                     use super::basic::*;\n\
                     use super::nameless_corpus::*;\n\
                     use super::nameless_guards::*;\n\
                     use super::snapshots::*;\n",
            );
            for (stem, path) in files {
                println!("cargo:rerun-if-changed={}", path.display());
                generated.push_str(&format!(
                    "    #[allow(dead_code, unused_imports)]\n\
                        mod {stem} {{\n\
                            use super::*;\n\
                            include!(r\"{}\");\n\
                        }}\n",
                    path.display()
                ));
            }
            generated.push_str("}\n");
        }
    }

    std::fs::write(out_dir.join("temporal.rs"), generated)
        .unwrap_or_else(|err| panic!("failed to write temporal.rs: {err}"));
}
