//! The decompilation-option catalogue: what the options are, what each
//! one does, and which panel section it belongs in — as data, so a UI
//! renders the option panel from the crate instead of keeping its own
//! copy of the list.
//!
//! 1. **The struct and the catalogue are one list.** The `pub struct`
//!    blocks are generated by [`macros::define_options`] /
//!    [`macros::define_pass_group`] from the same source text as the
//!    catalogue entries, so a field that is not in the catalogue does
//!    not exist; every way of writing one without its catalogue
//!    metadata is a macro parse error.
//! 2. **A total destructure.** [`DecompileOptions::values`] destructures
//!    the whole struct with no `..`, so a new field is `error[E0027]`
//!    until the value-reader names it.
//! 3. **A test.** rustc's own suggestion for that error is `field: _`,
//!    which compiles; `tests::every_ui_entry_is_readable_and_writable`
//!    walks the catalogue and sets-then-gets every exposed path, so a
//!    field that took the escape hatch while claiming a UI control
//!    fails the suite.
//!
//! Enum-valued options get the same treatment one level down: see
//! [`choices`].

pub(crate) mod catalogue;
pub(crate) mod choices;
pub(crate) mod macros;
#[cfg(test)]
mod tests;

pub use catalogue::{
    ChoicePayload, Exposure, GroupId, OptionChoice, OptionEntry, OptionGroup, OptionKind,
};
#[cfg(test)]
pub use choices::PURPOSE_NOT_OFFERED;
pub use choices::{
    APPLIED_KIND_CHOICES, OUTPUT_LAYER_CHOICES, PURPOSE_CHOICES, SCRIPT_KIND_CHOICES,
    SCRIPT_VERSION_CHOICES, SPLIT_PURPOSES_CHOICES,
};

use crate::decompile::validator_meta::ValidatorPurpose;
use crate::decompile::validator_shape::{AppliedKind, ScriptKind, SplitPurposes};
use crate::decompile::{
    DecompileOptions, DisplayPolishPasses, OutputLayer, ReadabilityPasses, ScriptVersion,
    SimplifyPasses, StructuralRecoveryPasses, TypePasses,
};

/// Bumped when the catalogue's SHAPE changes (a new [`OptionKind`], a
/// new payload form) — not when an option is added, which consumers
/// handle by construction.
pub const CATALOGUE_VERSION: u32 = 1;

/// The panel sections, in the order a UI should render them.
///
/// The first three are the blocks the web panel draws, separated by
/// `border-t` dividers; the last five are the crate's five pass
/// structs.
///
/// Membership is NOT listed here: each entry carries its own
/// [`GroupId`] and consumers partition by it, so there is no second
/// list to disagree with the first.
pub const GROUPS: &[OptionGroup] = &[
    OptionGroup {
        id: GroupId::PipelineSurface,
        title: "Pipeline & surface",
        summary: "Where the pipeline stops, and how the recovered program is spelled",
        detail: &[
            "Which layer to render, and the surface choices that apply once the full-decompilation layer is \
             reached: whether unresolved constructors get synthesized declarations, whether \
             prelude names are recognized, and how the un-recovered Data-access spine is \
             written.",
            "",
            "The layer comes first because it decides whether the rest applies at all: the UPLC \
             layers ignore every option below, and Raw pseudo / Post-pipeline render the bare \
             AST without the render-prep dressing.",
        ],
        master_path: None,
    },
    OptionGroup {
        id: GroupId::ScriptIdentification,
        title: "Script identification",
        summary: "Which Plutus version produced the bytecode",
        detail: &[
            "Drives the runtime calling convention and Cardano-domain field naming. Auto-detect \
             reads the UPLC header and refines a `(1,0,_)` header by scanning for V2/V3-only \
             builtins, so an explicit setting is mainly for disambiguating V1 from V2.",
        ],
        master_path: None,
    },
    OptionGroup {
        id: GroupId::ValidatorWrapShape,
        title: "Validator wrap shape",
        summary: "How the validator block around the body is shaped",
        detail: &[
            "Purpose, split policy and outer-Apply interpretation only matter once the \
             decompiler has decided to render the output as a validator block — they are no-ops \
             when Script Kind is Plain.",
        ],
        master_path: None,
    },
    OptionGroup {
        id: GroupId::Simplify,
        title: "Simplify",
        summary: "Inlining + fixed-point simplify",
        detail: &[
            "The beta-reduction / inlining / dead-let cluster. Disable the whole group (master \
             toggle off) for the equivalent of `--no-optimize` — every let binding the \
             simplifier would normally inline survives, useful for seeing the raw lambda graph.",
            "",
            "WARNING about leaf-level dependencies: turning off `simplify_fp_initial` REQUIRES \
             also turning off `inline_single_use` (it produces `consistent_ref_ids` which \
             inline_single_use requires); the API will return InvalidOptions otherwise.",
        ],
        master_path: Some(&["simplify_passes"]),
    },
    OptionGroup {
        id: GroupId::StructuralRecovery,
        title: "Structural recovery",
        summary: "Recover idiomatic patterns",
        detail: &[
            "Recover idiomatic control-flow patterns hidden inside the lambda calculus: \
             Z-combinator to named recursion, immediate lambda-application to let, Data.case to \
             when, etc. The whole group is also gated by Safe Mode — turning Safe Mode ON skips \
             this cluster entirely regardless of these leaf toggles.",
            "",
            "Most leaves are SHAPE-CONDITIONAL: they only fire on inputs that contain the \
             triggering pattern (Z-combinator literal, CPS-encoded selector, nested rec-fn, \
             etc.). On a typical well-simplified input the entire cluster ends up being a no-op \
             — output with all leaves off is bitwise-identical to default.",
        ],
        master_path: Some(&["structural_recovery_passes"]),
    },
    OptionGroup {
        id: GroupId::Readability,
        title: "Readability",
        summary: "Names, flattening, hoisting",
        detail: &[
            "Cosmetic readability transforms: synthesizing meaningful variable names, flattening \
             let chains into block style, hoisting repeated lambdas, and extracting heavy \
             literals into top-level constants. Group output is rendering-only — semantics never \
             change.",
            "",
            "With the cluster off, synthetic helper names leak through — `rec fn v_247(v_249)` \
             instead of `rec fn rec_fn_16(v_249)` — and heavy-constant extraction stops with it: \
             that pass is gated on this cluster's own `extract_heavy_constants` leaf, not on the \
             display-polish group.",
        ],
        master_path: Some(&["readability_passes"]),
    },
    OptionGroup {
        id: GroupId::DisplayPolish,
        title: "Display polish",
        summary: "Cosmetic rewrites",
        detail: &[
            "Late cosmetic rewrites that run after the simplify / structural / readability \
             pipeline has stabilized. None affect semantics — they just produce nicer-looking \
             output (list literals, eta'd selectors, boolean identity collapses, etc.). The \
             cluster is also gated by Safe Mode for the more aggressive members.",
            "",
            "Default renders `[entry, ..tail] -> [entry.fst, ..map(tail)]`; with the cluster off \
             the same arm reads `[v_33_h, ..v_33_t] -> List.cons(v_33_h.fst, map(v_33_t))`.",
        ],
        master_path: Some(&["display_polish_passes"]),
    },
    OptionGroup {
        id: GroupId::TypeInference,
        title: "Type inference",
        summary: "HM solver + propagation",
        detail: &[
            "The type pipeline: gather constraints from builtin usage, solve via Hindley-Milner \
             unification, propagate solved types onto vars, and run the \
             `resolve_cardano_field_names` rewrite that maps `script_context.fields[N]` to real \
             field names. Turn the master toggle off for the `--no-types` equivalent — output \
             drops the `: Type` annotations on let bindings and constants.",
            "",
            "Cardano-domain field naming is robust across this toggle: a parallel `VarKind`-based \
             naming layer also produces `script_context.tx_info.signatories`, so `--no-types` \
             alone does NOT collapse those back to `fields[0].fields[0]`.",
            "",
            "WARNING: strict dependency chain. solve_type_constraints produces \
             TypeConstraintsSolved, required by propagate_types, which produces TypesPropagated, \
             required by resolve_cardano_field_names. Turning off any link requires turning off \
             every leaf to its right; the API returns InvalidOptions otherwise.",
        ],
        master_path: Some(&["type_passes"]),
    },
];

/// Every option a user can see and set, in declaration order, with the
/// five pass groups and the validator-shape struct flattened into their
/// members.
///
/// The only allocating function in this module: one `Vec` of
/// references, built per call.
pub fn ui_options() -> Vec<&'static OptionEntry> {
    let mut out = Vec::new();
    collect_ui(DecompileOptions::ENTRIES, &mut out);
    out
}

fn collect_ui(entries: &'static [OptionEntry], out: &mut Vec<&'static OptionEntry>) {
    for entry in entries {
        match entry.exposure {
            Exposure::Ui { .. } => out.push(entry),
            Exposure::Nested { members } => collect_ui(members, out),
            Exposure::Internal { .. } => {}
        }
    }
}

/// Every option in one group, in declaration order.
pub fn ui_options_in(group: GroupId) -> Vec<&'static OptionEntry> {
    ui_options()
        .into_iter()
        .filter(|e| matches!(e.exposure, Exposure::Ui { group: g, .. } if g == group))
        .collect()
}

/// The value of one option, in the catalogue's own vocabulary.
///
/// `Choice` carries a `&'static str` on purpose: a value written back
/// into the options struct is resolved by matching against the tokens
/// the catalogue DECLARED, never parsed out of a rendered string.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OptionValue {
    /// A [`OptionKind::Toggle`].
    Bool(bool),
    /// A [`OptionKind::Choice`]; `None` is the `unset` state of an
    /// `Option<_>`-typed field.
    Choice(Option<&'static str>),
    /// A [`OptionKind::Choice`] whose selected variant carries a
    /// [`ChoicePayload::Count`].
    Count(u32),
}

/// Why a write to an option path was refused.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum OptionSetError {
    /// No catalogue entry has this path.
    UnknownPath(String),
    /// The path exists but holds a different kind of value.
    TypeMismatch {
        /// The path that was written.
        path: String,
        /// What that path accepts.
        expected: &'static str,
    },
    /// The path exists and is a choice, but the token is not one it
    /// declares.
    UnknownChoice {
        /// The path that was written.
        path: String,
        /// The token that was offered.
        got: String,
    },
}

impl std::fmt::Display for OptionSetError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnknownPath(path) => write!(f, "unknown option `{path}`"),
            Self::TypeMismatch { path, expected } => {
                write!(f, "option `{path}` expects {expected}")
            }
            Self::UnknownChoice { path, got } => {
                write!(f, "option `{path}` has no choice `{got}`")
            }
        }
    }
}

impl std::error::Error for OptionSetError {}

fn joined(path: &[&str]) -> String {
    path.join(".")
}

/// Find the declared choice whose `value` equals `token`, for the
/// catalogue entry at `path`.
fn declared_choice(path: &[&str], token: &str) -> Option<&'static OptionChoice> {
    let entry = ui_options().into_iter().find(|e| e.path == path)?;
    let (_, _, kind, _) = entry.ui()?;
    match kind {
        OptionKind::Toggle => None,
        OptionKind::Choice { choices, .. } => choices.iter().find(|c| c.value == token),
    }
}

impl DecompileOptions {
    /// Read every catalogue-exposed value out of `self`.
    ///
    /// The destructure below is TOTAL — no `..` — so a new
    /// [`DecompileOptions`] field is `error[E0027]` here until the
    /// reader names it. rustc's `field: _` escape hatch compiles,
    /// which `tests::every_ui_entry_is_readable_and_writable` catches.
    fn values(&self) -> Vec<(&'static [&'static str], OptionValue)> {
        let Self {
            safe_mode,
            script_version,
            blueprint_hints: _,
            validator_meta: _,
            use_varkind_recovery: _,
            synthesize_stub_adts,
            validator_shape,
            recognize_prelude_constructors,
            decode_church_to_native,
            expect_or_fail,
            compilable_data_access,
            strip_all_traces,
            strip_plutustx_traces,
            ordering_names,
            output_layer,
            simplify_passes,
            structural_recovery_passes,
            readability_passes,
            display_polish_passes,
            type_passes,
            oracle_data_args: _,
            oracle_tx: _,
            record_lineage_routes: _,
        } = self;

        let mut out: Vec<(&'static [&'static str], OptionValue)> = vec![
            (&["safe_mode"], OptionValue::Bool(*safe_mode)),
            (
                &["script_version"],
                OptionValue::Choice(script_version.map(ScriptVersion::wire_token)),
            ),
            (
                &["synthesize_stub_adts"],
                OptionValue::Bool(*synthesize_stub_adts),
            ),
            (
                &["recognize_prelude_constructors"],
                OptionValue::Bool(*recognize_prelude_constructors),
            ),
            (
                &["decode_church_to_native"],
                OptionValue::Bool(*decode_church_to_native),
            ),
            (&["expect_or_fail"], OptionValue::Bool(*expect_or_fail)),
            (
                &["compilable_data_access"],
                OptionValue::Bool(*compilable_data_access),
            ),
            (&["strip_all_traces"], OptionValue::Bool(*strip_all_traces)),
            (
                &["strip_plutustx_traces"],
                OptionValue::Bool(*strip_plutustx_traces),
            ),
            (&["ordering_names"], OptionValue::Bool(*ordering_names)),
            (
                &["output_layer"],
                OptionValue::Choice(Some(output_layer.wire_token())),
            ),
            (
                &["validator_shape", "purpose"],
                OptionValue::Choice(validator_shape.purpose.map(ValidatorPurpose::wire_token)),
            ),
            (
                &["validator_shape", "split_purposes"],
                OptionValue::Choice(Some(validator_shape.split_purposes.wire_token())),
            ),
            (
                &["validator_shape", "script_kind"],
                OptionValue::Choice(validator_shape.script_kind.map(ScriptKind::wire_token)),
            ),
            (
                &["validator_shape", "applied_kind"],
                match validator_shape.applied_kind {
                    AppliedKind::RuntimeCount(n) => OptionValue::Count(n as u32),
                    other => OptionValue::Choice(Some(other.wire_token())),
                },
            ),
        ];

        let mut push_group = |entries: &'static [OptionEntry],
                              read: &dyn Fn(&str) -> Option<bool>| {
            for entry in entries {
                let value = read(entry.field).expect(
                    "a pass group's ENTRIES and its `get` come from one macro list, so \
                         every entry resolves",
                );
                out.push((entry.path, OptionValue::Bool(value)));
            }
        };
        push_group(SimplifyPasses::ENTRIES, &|f| simplify_passes.get(f));
        push_group(StructuralRecoveryPasses::ENTRIES, &|f| {
            structural_recovery_passes.get(f)
        });
        push_group(ReadabilityPasses::ENTRIES, &|f| readability_passes.get(f));
        push_group(DisplayPolishPasses::ENTRIES, &|f| {
            display_polish_passes.get(f)
        });
        push_group(TypePasses::ENTRIES, &|f| type_passes.get(f));
        // `push_group` borrowed `out` mutably; NLL ends that borrow at its
        // last use, so `out` is free to move below without an explicit drop.

        out
    }

    /// Read one option by its catalogue path.
    pub fn get(&self, path: &[&str]) -> Option<OptionValue> {
        self.values()
            .into_iter()
            .find(|(p, _)| *p == path)
            .map(|(_, v)| v)
    }

    /// Write one option by its catalogue path.
    ///
    /// A [`OptionValue::Choice`] token is resolved by matching
    /// against the choices the catalogue DECLARES for that path,
    /// never by `parse()` of a rendered string.
    pub(crate) fn set(&mut self, path: &[&str], value: OptionValue) -> Result<(), OptionSetError> {
        let mismatch = |expected| {
            Err(OptionSetError::TypeMismatch {
                path: joined(path),
                expected,
            })
        };
        let unknown_choice = |token: &str| {
            Err(OptionSetError::UnknownChoice {
                path: joined(path),
                got: token.to_string(),
            })
        };

        match path {
            ["safe_mode"] => match value {
                OptionValue::Bool(v) => self.safe_mode = v,
                _ => return mismatch("a boolean"),
            },
            ["synthesize_stub_adts"] => match value {
                OptionValue::Bool(v) => self.synthesize_stub_adts = v,
                _ => return mismatch("a boolean"),
            },
            ["recognize_prelude_constructors"] => match value {
                OptionValue::Bool(v) => self.recognize_prelude_constructors = v,
                _ => return mismatch("a boolean"),
            },
            ["decode_church_to_native"] => match value {
                OptionValue::Bool(v) => self.decode_church_to_native = v,
                _ => return mismatch("a boolean"),
            },
            ["expect_or_fail"] => match value {
                OptionValue::Bool(v) => self.expect_or_fail = v,
                _ => return mismatch("a boolean"),
            },
            ["compilable_data_access"] => match value {
                OptionValue::Bool(v) => self.compilable_data_access = v,
                _ => return mismatch("a boolean"),
            },
            ["strip_all_traces"] => match value {
                OptionValue::Bool(v) => self.strip_all_traces = v,
                _ => return mismatch("a boolean"),
            },
            ["strip_plutustx_traces"] => match value {
                OptionValue::Bool(v) => self.strip_plutustx_traces = v,
                _ => return mismatch("a boolean"),
            },
            ["ordering_names"] => match value {
                OptionValue::Bool(v) => self.ordering_names = v,
                _ => return mismatch("a boolean"),
            },
            ["script_version"] => match value {
                OptionValue::Choice(None) => self.script_version = None,
                OptionValue::Choice(Some(token)) => {
                    let Some(v) = ScriptVersion::ALL
                        .into_iter()
                        .find(|v| v.wire_token() == token)
                    else {
                        return unknown_choice(token);
                    };
                    self.script_version = Some(v);
                }
                _ => return mismatch("a script version"),
            },
            ["output_layer"] => match value {
                OptionValue::Choice(Some(token)) => {
                    let Some(v) = OutputLayer::ALL
                        .into_iter()
                        .find(|v| v.wire_token() == token)
                    else {
                        return unknown_choice(token);
                    };
                    self.output_layer = v;
                }
                _ => return mismatch("an output layer"),
            },
            ["validator_shape", "purpose"] => match value {
                OptionValue::Choice(None) => self.validator_shape.purpose = None,
                OptionValue::Choice(Some(token)) => {
                    if declared_choice(path, token).is_none() {
                        return unknown_choice(token);
                    }
                    let Some(v) = ValidatorPurpose::ALL
                        .into_iter()
                        .find(|v| v.wire_token() == token)
                    else {
                        return unknown_choice(token);
                    };
                    self.validator_shape.purpose = Some(v);
                }
                _ => return mismatch("a validator purpose"),
            },
            ["validator_shape", "split_purposes"] => match value {
                OptionValue::Choice(Some(token)) => {
                    let Some(v) = SplitPurposes::ALL
                        .into_iter()
                        .find(|v| v.wire_token() == token)
                    else {
                        return unknown_choice(token);
                    };
                    self.validator_shape.split_purposes = v;
                }
                _ => return mismatch("a split-purposes policy"),
            },
            ["validator_shape", "script_kind"] => match value {
                OptionValue::Choice(None) => self.validator_shape.script_kind = None,
                OptionValue::Choice(Some(token)) => {
                    let Some(v) = ScriptKind::ALL
                        .into_iter()
                        .find(|v| v.wire_token() == token)
                    else {
                        return unknown_choice(token);
                    };
                    self.validator_shape.script_kind = Some(v);
                }
                _ => return mismatch("a script kind"),
            },
            ["validator_shape", "applied_kind"] => match value {
                // An explicit split arrives as its count.
                OptionValue::Count(n) => {
                    self.validator_shape.applied_kind = AppliedKind::RuntimeCount(n as usize);
                }
                OptionValue::Choice(Some(token)) => {
                    let Some(choice) = declared_choice(path, token) else {
                        return unknown_choice(token);
                    };
                    // Picking the count-carrying choice with no count
                    // means "use the count the catalogue declares".
                    self.validator_shape.applied_kind = match choice.payload {
                        Some(ChoicePayload::Count { default, .. }) => {
                            AppliedKind::RuntimeCount(default as usize)
                        }
                        None => {
                            let Some(v) = AppliedKind::ALL
                                .into_iter()
                                .find(|v| v.wire_token() == token)
                            else {
                                return unknown_choice(token);
                            };
                            v
                        }
                    };
                }
                _ => return mismatch("an outer-Apply interpretation"),
            },
            [group, leaf] => {
                let OptionValue::Bool(v) = value else {
                    return mismatch("a boolean");
                };
                let applied = match *group {
                    "simplify_passes" => self.simplify_passes.set(leaf, v),
                    "structural_recovery_passes" => self.structural_recovery_passes.set(leaf, v),
                    "readability_passes" => self.readability_passes.set(leaf, v),
                    "display_polish_passes" => self.display_polish_passes.set(leaf, v),
                    "type_passes" => self.type_passes.set(leaf, v),
                    _ => false,
                };
                if !applied {
                    return Err(OptionSetError::UnknownPath(joined(path)));
                }
            }
            _ => return Err(OptionSetError::UnknownPath(joined(path))),
        }
        Ok(())
    }
}
