pub(crate) use super::*;
pub(crate) use crate::pseudo::ast::{BinaryOp, PseudoExpr};
pub(crate) use crate::pseudo::var_id::VarId;
pub(crate) use std::collections::{HashMap, HashSet};

mod accumulator;
mod basic_hint;
mod cached_key_lookup_helper;
mod check_temp_display_hint;
mod constructor_pattern_hint;
mod contains;
mod data_list_temp;
mod extractor_field_stem;
mod extractor_temp;
mod extractor_temp_alias;
mod field_payload_temp;
mod filter_matches;
mod filter_matches_improve_guard;
mod fold_map;
mod fold_map_improve_guard;
mod forwarded_wrapper;
mod get_at;
mod get_at_improve_guard;
mod get_at_param_rename;
mod if_empty_direct;
mod if_empty_lookup;
mod int_helper;
mod known_function_result;
mod known_function_result_improve_guard;
mod list_any;
mod list_any_identity_guard;
mod list_find;
mod list_helper_param_rename;
mod list_helper_wrapper_param_rename;
mod lookup_false_like_param_rename;
mod lookup_nested_improve;
mod lookup_nested_improve_guard;
mod lookup_nested_int;
mod lookup_nested_map;
mod lookup_param_rename;
mod lookup_rec;
mod lookup_single_letter;
mod lookup_then;
mod nameless_owner_alias;
mod param_hint_guard;
mod scope_guard;
mod single_param_list_rec;
mod temp_binding_analysis;
mod utility;
mod when_body_extractor;
